env:
  browser: true
  es2021: true
  'jest/globals': true
settings:
  react:
    version: detect
  jest:
    version: 26
extends:
  - 'plugin:react/recommended'
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - jest
  - '@typescript-eslint'
rules: {
  'react/react-in-jsx-scope': 'off',
  'no-unused-vars': 'off',
  'no-use-before-define': 'off',
  'no-useless-constructor': 'off',
  '@typescript-eslint/no-unused-vars': 'error',
  '@typescript-eslint/no-use-before-define': 'error',
  '@typescript-eslint/no-useless-constructor': 'error'
}
